version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: f1-mongo-java
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: f1-backend-java
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/f1db
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: f1-frontend-java
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/static:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  mongo_data:
